<?xml version="1.0" encoding="utf-8"?><Database Name="cvoorber" Class="faqsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=cvoorber.db.10296660.hostedresource.com;Initial Catalog=cvoorber;Persist Security Info=True;User ID=cvoorber" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="cvoorberConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ndmh_faqs" Member="ndmh_faqs">
    <Type Name="ndmh_faq">
      <Column Name="ndmh_faq_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ndmh_faq_title" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>