#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="cvoorber")]
public partial class faqsDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertndmh_faq(ndmh_faq instance);
  partial void Updatendmh_faq(ndmh_faq instance);
  partial void Deletendmh_faq(ndmh_faq instance);
  #endregion
	
	public faqsDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["cvoorberConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public faqsDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public faqsDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public faqsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public faqsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<ndmh_faq> ndmh_faqs
	{
		get
		{
			return this.GetTable<ndmh_faq>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ndmh_faqs")]
public partial class ndmh_faq : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ndmh_faq_id;
	
	private string _ndmh_faq_title;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onndmh_faq_idChanging(int value);
    partial void Onndmh_faq_idChanged();
    partial void Onndmh_faq_titleChanging(string value);
    partial void Onndmh_faq_titleChanged();
    #endregion
	
	public ndmh_faq()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ndmh_faq_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ndmh_faq_id
	{
		get
		{
			return this._ndmh_faq_id;
		}
		set
		{
			if ((this._ndmh_faq_id != value))
			{
				this.Onndmh_faq_idChanging(value);
				this.SendPropertyChanging();
				this._ndmh_faq_id = value;
				this.SendPropertyChanged("ndmh_faq_id");
				this.Onndmh_faq_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ndmh_faq_title", DbType="VarChar(1000)")]
	public string ndmh_faq_title
	{
		get
		{
			return this._ndmh_faq_title;
		}
		set
		{
			if ((this._ndmh_faq_title != value))
			{
				this.Onndmh_faq_titleChanging(value);
				this.SendPropertyChanging();
				this._ndmh_faq_title = value;
				this.SendPropertyChanged("ndmh_faq_title");
				this.Onndmh_faq_titleChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
