#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="cvoorber")]
public partial class get_pageDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertndmh_report(ndmh_report instance);
  partial void Updatendmh_report(ndmh_report instance);
  partial void Deletendmh_report(ndmh_report instance);
  partial void Insertndmh_general_page(ndmh_general_page instance);
  partial void Updatendmh_general_page(ndmh_general_page instance);
  partial void Deletendmh_general_page(ndmh_general_page instance);
  #endregion
	
	public get_pageDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["cvoorberConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public get_pageDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public get_pageDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public get_pageDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public get_pageDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<ndmh_report> ndmh_reports
	{
		get
		{
			return this.GetTable<ndmh_report>();
		}
	}
	
	public System.Data.Linq.Table<ndmh_general_page> ndmh_general_pages
	{
		get
		{
			return this.GetTable<ndmh_general_page>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ndmh_reports")]
public partial class ndmh_report : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _r_id;
	
	private string _r_title;
	
	private string _r_importance;
	
	private System.Nullable<System.DateTime> _r_date;
	
	private string _r_content;
	
	private System.Data.Linq.Binary _r_image;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onr_idChanging(int value);
    partial void Onr_idChanged();
    partial void Onr_titleChanging(string value);
    partial void Onr_titleChanged();
    partial void Onr_importanceChanging(string value);
    partial void Onr_importanceChanged();
    partial void Onr_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onr_dateChanged();
    partial void Onr_contentChanging(string value);
    partial void Onr_contentChanged();
    partial void Onr_imageChanging(System.Data.Linq.Binary value);
    partial void Onr_imageChanged();
    #endregion
	
	public ndmh_report()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int r_id
	{
		get
		{
			return this._r_id;
		}
		set
		{
			if ((this._r_id != value))
			{
				this.Onr_idChanging(value);
				this.SendPropertyChanging();
				this._r_id = value;
				this.SendPropertyChanged("r_id");
				this.Onr_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_title", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string r_title
	{
		get
		{
			return this._r_title;
		}
		set
		{
			if ((this._r_title != value))
			{
				this.Onr_titleChanging(value);
				this.SendPropertyChanging();
				this._r_title = value;
				this.SendPropertyChanged("r_title");
				this.Onr_titleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_importance", DbType="NChar(10)")]
	public string r_importance
	{
		get
		{
			return this._r_importance;
		}
		set
		{
			if ((this._r_importance != value))
			{
				this.Onr_importanceChanging(value);
				this.SendPropertyChanging();
				this._r_importance = value;
				this.SendPropertyChanged("r_importance");
				this.Onr_importanceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_date", DbType="Date")]
	public System.Nullable<System.DateTime> r_date
	{
		get
		{
			return this._r_date;
		}
		set
		{
			if ((this._r_date != value))
			{
				this.Onr_dateChanging(value);
				this.SendPropertyChanging();
				this._r_date = value;
				this.SendPropertyChanged("r_date");
				this.Onr_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string r_content
	{
		get
		{
			return this._r_content;
		}
		set
		{
			if ((this._r_content != value))
			{
				this.Onr_contentChanging(value);
				this.SendPropertyChanging();
				this._r_content = value;
				this.SendPropertyChanged("r_content");
				this.Onr_contentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary r_image
	{
		get
		{
			return this._r_image;
		}
		set
		{
			if ((this._r_image != value))
			{
				this.Onr_imageChanging(value);
				this.SendPropertyChanging();
				this._r_image = value;
				this.SendPropertyChanged("r_image");
				this.Onr_imageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ndmh_general_pages")]
public partial class ndmh_general_page : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _gp_id;
	
	private string _gp_title;
	
	private string _gp_content;
	
	private System.Data.Linq.Binary _gp_image;
	
	private string _gp_section;
	
	private string _gp_active;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongp_idChanging(int value);
    partial void Ongp_idChanged();
    partial void Ongp_titleChanging(string value);
    partial void Ongp_titleChanged();
    partial void Ongp_contentChanging(string value);
    partial void Ongp_contentChanged();
    partial void Ongp_imageChanging(System.Data.Linq.Binary value);
    partial void Ongp_imageChanged();
    partial void Ongp_sectionChanging(string value);
    partial void Ongp_sectionChanged();
    partial void Ongp_activeChanging(string value);
    partial void Ongp_activeChanged();
    #endregion
	
	public ndmh_general_page()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gp_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int gp_id
	{
		get
		{
			return this._gp_id;
		}
		set
		{
			if ((this._gp_id != value))
			{
				this.Ongp_idChanging(value);
				this.SendPropertyChanging();
				this._gp_id = value;
				this.SendPropertyChanged("gp_id");
				this.Ongp_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gp_title", DbType="VarChar(50)")]
	public string gp_title
	{
		get
		{
			return this._gp_title;
		}
		set
		{
			if ((this._gp_title != value))
			{
				this.Ongp_titleChanging(value);
				this.SendPropertyChanging();
				this._gp_title = value;
				this.SendPropertyChanged("gp_title");
				this.Ongp_titleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gp_content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string gp_content
	{
		get
		{
			return this._gp_content;
		}
		set
		{
			if ((this._gp_content != value))
			{
				this.Ongp_contentChanging(value);
				this.SendPropertyChanging();
				this._gp_content = value;
				this.SendPropertyChanged("gp_content");
				this.Ongp_contentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gp_image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary gp_image
	{
		get
		{
			return this._gp_image;
		}
		set
		{
			if ((this._gp_image != value))
			{
				this.Ongp_imageChanging(value);
				this.SendPropertyChanging();
				this._gp_image = value;
				this.SendPropertyChanged("gp_image");
				this.Ongp_imageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gp_section", DbType="VarChar(30)")]
	public string gp_section
	{
		get
		{
			return this._gp_section;
		}
		set
		{
			if ((this._gp_section != value))
			{
				this.Ongp_sectionChanging(value);
				this.SendPropertyChanging();
				this._gp_section = value;
				this.SendPropertyChanged("gp_section");
				this.Ongp_sectionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gp_active", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
	public string gp_active
	{
		get
		{
			return this._gp_active;
		}
		set
		{
			if ((this._gp_active != value))
			{
				this.Ongp_activeChanging(value);
				this.SendPropertyChanging();
				this._gp_active = value;
				this.SendPropertyChanged("gp_active");
				this.Ongp_activeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
