<?xml version="1.0" encoding="utf-8"?><Database Name="cvoorber" Class="get_pageDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=cvoorber.db.10296660.hostedresource.com;Initial Catalog=cvoorber;Persist Security Info=True;User ID=cvoorber" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="cvoorberConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ndmh_reports" Member="ndmh_reports">
    <Type Name="ndmh_report">
      <Column Name="r_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="r_title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="r_importance" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="r_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="r_content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="r_image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.ndmh_general_pages" Member="ndmh_general_pages">
    <Type Name="ndmh_general_page">
      <Column Name="gp_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gp_title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="gp_content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="gp_image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="gp_section" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="gp_active" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>