#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="cvoorber")]
public partial class VirtTourDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertndmh_department_listing(ndmh_department_listing instance);
  partial void Updatendmh_department_listing(ndmh_department_listing instance);
  partial void Deletendmh_department_listing(ndmh_department_listing instance);
  #endregion
	
	public VirtTourDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["cvoorberConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public VirtTourDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VirtTourDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VirtTourDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VirtTourDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<ndmh_department_listing> ndmh_department_listings
	{
		get
		{
			return this.GetTable<ndmh_department_listing>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ndmh_department_listing")]
public partial class ndmh_department_listing : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _dl_id;
	
	private string _dl_name;
	
	private System.Nullable<int> _dl_extention;
	
	private System.Nullable<System.TimeSpan> _dl_open_hour;
	
	private System.Nullable<System.TimeSpan> _dl_close_hour;
	
	private string _dl_days_open;
	
	private System.Nullable<int> _dl_floor_no;
	
	private System.Nullable<int> _dl_room_no;
	
	private string _dl_description;
	
	private string _dl_img_url;
	
	private string _dl_img_alt;
	
	private string _dl_img_desc;
	
	private System.Nullable<int> _dl_img_width;
	
	private System.Nullable<int> _dl_img_height;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondl_idChanging(int value);
    partial void Ondl_idChanged();
    partial void Ondl_nameChanging(string value);
    partial void Ondl_nameChanged();
    partial void Ondl_extentionChanging(System.Nullable<int> value);
    partial void Ondl_extentionChanged();
    partial void Ondl_open_hourChanging(System.Nullable<System.TimeSpan> value);
    partial void Ondl_open_hourChanged();
    partial void Ondl_close_hourChanging(System.Nullable<System.TimeSpan> value);
    partial void Ondl_close_hourChanged();
    partial void Ondl_days_openChanging(string value);
    partial void Ondl_days_openChanged();
    partial void Ondl_floor_noChanging(System.Nullable<int> value);
    partial void Ondl_floor_noChanged();
    partial void Ondl_room_noChanging(System.Nullable<int> value);
    partial void Ondl_room_noChanged();
    partial void Ondl_descriptionChanging(string value);
    partial void Ondl_descriptionChanged();
    partial void Ondl_img_urlChanging(string value);
    partial void Ondl_img_urlChanged();
    partial void Ondl_img_altChanging(string value);
    partial void Ondl_img_altChanged();
    partial void Ondl_img_descChanging(string value);
    partial void Ondl_img_descChanged();
    partial void Ondl_img_widthChanging(System.Nullable<int> value);
    partial void Ondl_img_widthChanged();
    partial void Ondl_img_heightChanging(System.Nullable<int> value);
    partial void Ondl_img_heightChanged();
    #endregion
	
	public ndmh_department_listing()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int dl_id
	{
		get
		{
			return this._dl_id;
		}
		set
		{
			if ((this._dl_id != value))
			{
				this.Ondl_idChanging(value);
				this.SendPropertyChanging();
				this._dl_id = value;
				this.SendPropertyChanged("dl_id");
				this.Ondl_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_name", DbType="VarChar(50)")]
	public string dl_name
	{
		get
		{
			return this._dl_name;
		}
		set
		{
			if ((this._dl_name != value))
			{
				this.Ondl_nameChanging(value);
				this.SendPropertyChanging();
				this._dl_name = value;
				this.SendPropertyChanged("dl_name");
				this.Ondl_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_extention", DbType="Int")]
	public System.Nullable<int> dl_extention
	{
		get
		{
			return this._dl_extention;
		}
		set
		{
			if ((this._dl_extention != value))
			{
				this.Ondl_extentionChanging(value);
				this.SendPropertyChanging();
				this._dl_extention = value;
				this.SendPropertyChanged("dl_extention");
				this.Ondl_extentionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_open_hour", DbType="Time")]
	public System.Nullable<System.TimeSpan> dl_open_hour
	{
		get
		{
			return this._dl_open_hour;
		}
		set
		{
			if ((this._dl_open_hour != value))
			{
				this.Ondl_open_hourChanging(value);
				this.SendPropertyChanging();
				this._dl_open_hour = value;
				this.SendPropertyChanged("dl_open_hour");
				this.Ondl_open_hourChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_close_hour", DbType="Time")]
	public System.Nullable<System.TimeSpan> dl_close_hour
	{
		get
		{
			return this._dl_close_hour;
		}
		set
		{
			if ((this._dl_close_hour != value))
			{
				this.Ondl_close_hourChanging(value);
				this.SendPropertyChanging();
				this._dl_close_hour = value;
				this.SendPropertyChanged("dl_close_hour");
				this.Ondl_close_hourChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_days_open", DbType="VarChar(50)")]
	public string dl_days_open
	{
		get
		{
			return this._dl_days_open;
		}
		set
		{
			if ((this._dl_days_open != value))
			{
				this.Ondl_days_openChanging(value);
				this.SendPropertyChanging();
				this._dl_days_open = value;
				this.SendPropertyChanged("dl_days_open");
				this.Ondl_days_openChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_floor_no", DbType="Int")]
	public System.Nullable<int> dl_floor_no
	{
		get
		{
			return this._dl_floor_no;
		}
		set
		{
			if ((this._dl_floor_no != value))
			{
				this.Ondl_floor_noChanging(value);
				this.SendPropertyChanging();
				this._dl_floor_no = value;
				this.SendPropertyChanged("dl_floor_no");
				this.Ondl_floor_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_room_no", DbType="Int")]
	public System.Nullable<int> dl_room_no
	{
		get
		{
			return this._dl_room_no;
		}
		set
		{
			if ((this._dl_room_no != value))
			{
				this.Ondl_room_noChanging(value);
				this.SendPropertyChanging();
				this._dl_room_no = value;
				this.SendPropertyChanged("dl_room_no");
				this.Ondl_room_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_description", DbType="VarChar(1000)")]
	public string dl_description
	{
		get
		{
			return this._dl_description;
		}
		set
		{
			if ((this._dl_description != value))
			{
				this.Ondl_descriptionChanging(value);
				this.SendPropertyChanging();
				this._dl_description = value;
				this.SendPropertyChanged("dl_description");
				this.Ondl_descriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_img_url", DbType="VarChar(1000)")]
	public string dl_img_url
	{
		get
		{
			return this._dl_img_url;
		}
		set
		{
			if ((this._dl_img_url != value))
			{
				this.Ondl_img_urlChanging(value);
				this.SendPropertyChanging();
				this._dl_img_url = value;
				this.SendPropertyChanged("dl_img_url");
				this.Ondl_img_urlChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_img_alt", DbType="VarChar(1000)")]
	public string dl_img_alt
	{
		get
		{
			return this._dl_img_alt;
		}
		set
		{
			if ((this._dl_img_alt != value))
			{
				this.Ondl_img_altChanging(value);
				this.SendPropertyChanging();
				this._dl_img_alt = value;
				this.SendPropertyChanged("dl_img_alt");
				this.Ondl_img_altChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_img_desc", DbType="VarChar(1000)")]
	public string dl_img_desc
	{
		get
		{
			return this._dl_img_desc;
		}
		set
		{
			if ((this._dl_img_desc != value))
			{
				this.Ondl_img_descChanging(value);
				this.SendPropertyChanging();
				this._dl_img_desc = value;
				this.SendPropertyChanged("dl_img_desc");
				this.Ondl_img_descChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_img_width", DbType="Int")]
	public System.Nullable<int> dl_img_width
	{
		get
		{
			return this._dl_img_width;
		}
		set
		{
			if ((this._dl_img_width != value))
			{
				this.Ondl_img_widthChanging(value);
				this.SendPropertyChanging();
				this._dl_img_width = value;
				this.SendPropertyChanged("dl_img_width");
				this.Ondl_img_widthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_img_height", DbType="Int")]
	public System.Nullable<int> dl_img_height
	{
		get
		{
			return this._dl_img_height;
		}
		set
		{
			if ((this._dl_img_height != value))
			{
				this.Ondl_img_heightChanging(value);
				this.SendPropertyChanging();
				this._dl_img_height = value;
				this.SendPropertyChanged("dl_img_height");
				this.Ondl_img_heightChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
