#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="cvoorber")]
public partial class VirtTourDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertndmh_department_listing(ndmh_department_listing instance);
  partial void Updatendmh_department_listing(ndmh_department_listing instance);
  partial void Deletendmh_department_listing(ndmh_department_listing instance);
  partial void Insertndmh_dep_list_image(ndmh_dep_list_image instance);
  partial void Updatendmh_dep_list_image(ndmh_dep_list_image instance);
  partial void Deletendmh_dep_list_image(ndmh_dep_list_image instance);
  #endregion
	
	public VirtTourDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["cvoorberConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public VirtTourDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VirtTourDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VirtTourDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public VirtTourDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<ndmh_department_listing> ndmh_department_listings
	{
		get
		{
			return this.GetTable<ndmh_department_listing>();
		}
	}
	
	public System.Data.Linq.Table<ndmh_dep_list_image> ndmh_dep_list_images
	{
		get
		{
			return this.GetTable<ndmh_dep_list_image>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ndmh_department_listing")]
public partial class ndmh_department_listing : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _dl_id;
	
	private string _dl_name;
	
	private System.Nullable<int> _dl_extention;
	
	private System.Nullable<System.TimeSpan> _dl_open_hour;
	
	private System.Nullable<System.TimeSpan> _dl_close_hour;
	
	private string _dl_days_open;
	
	private System.Nullable<int> _dl_floor_no;
	
	private System.Nullable<int> _dl_room_no;
	
	private string _dl_description;
	
	private EntitySet<ndmh_dep_list_image> _ndmh_dep_list_images;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondl_idChanging(int value);
    partial void Ondl_idChanged();
    partial void Ondl_nameChanging(string value);
    partial void Ondl_nameChanged();
    partial void Ondl_extentionChanging(System.Nullable<int> value);
    partial void Ondl_extentionChanged();
    partial void Ondl_open_hourChanging(System.Nullable<System.TimeSpan> value);
    partial void Ondl_open_hourChanged();
    partial void Ondl_close_hourChanging(System.Nullable<System.TimeSpan> value);
    partial void Ondl_close_hourChanged();
    partial void Ondl_days_openChanging(string value);
    partial void Ondl_days_openChanged();
    partial void Ondl_floor_noChanging(System.Nullable<int> value);
    partial void Ondl_floor_noChanged();
    partial void Ondl_room_noChanging(System.Nullable<int> value);
    partial void Ondl_room_noChanged();
    partial void Ondl_descriptionChanging(string value);
    partial void Ondl_descriptionChanged();
    #endregion
	
	public ndmh_department_listing()
	{
		this._ndmh_dep_list_images = new EntitySet<ndmh_dep_list_image>(new Action<ndmh_dep_list_image>(this.attach_ndmh_dep_list_images), new Action<ndmh_dep_list_image>(this.detach_ndmh_dep_list_images));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int dl_id
	{
		get
		{
			return this._dl_id;
		}
		set
		{
			if ((this._dl_id != value))
			{
				this.Ondl_idChanging(value);
				this.SendPropertyChanging();
				this._dl_id = value;
				this.SendPropertyChanged("dl_id");
				this.Ondl_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_name", DbType="VarChar(50)")]
	public string dl_name
	{
		get
		{
			return this._dl_name;
		}
		set
		{
			if ((this._dl_name != value))
			{
				this.Ondl_nameChanging(value);
				this.SendPropertyChanging();
				this._dl_name = value;
				this.SendPropertyChanged("dl_name");
				this.Ondl_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_extention", DbType="Int")]
	public System.Nullable<int> dl_extention
	{
		get
		{
			return this._dl_extention;
		}
		set
		{
			if ((this._dl_extention != value))
			{
				this.Ondl_extentionChanging(value);
				this.SendPropertyChanging();
				this._dl_extention = value;
				this.SendPropertyChanged("dl_extention");
				this.Ondl_extentionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_open_hour", DbType="Time")]
	public System.Nullable<System.TimeSpan> dl_open_hour
	{
		get
		{
			return this._dl_open_hour;
		}
		set
		{
			if ((this._dl_open_hour != value))
			{
				this.Ondl_open_hourChanging(value);
				this.SendPropertyChanging();
				this._dl_open_hour = value;
				this.SendPropertyChanged("dl_open_hour");
				this.Ondl_open_hourChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_close_hour", DbType="Time")]
	public System.Nullable<System.TimeSpan> dl_close_hour
	{
		get
		{
			return this._dl_close_hour;
		}
		set
		{
			if ((this._dl_close_hour != value))
			{
				this.Ondl_close_hourChanging(value);
				this.SendPropertyChanging();
				this._dl_close_hour = value;
				this.SendPropertyChanged("dl_close_hour");
				this.Ondl_close_hourChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_days_open", DbType="VarChar(50)")]
	public string dl_days_open
	{
		get
		{
			return this._dl_days_open;
		}
		set
		{
			if ((this._dl_days_open != value))
			{
				this.Ondl_days_openChanging(value);
				this.SendPropertyChanging();
				this._dl_days_open = value;
				this.SendPropertyChanged("dl_days_open");
				this.Ondl_days_openChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_floor_no", DbType="Int")]
	public System.Nullable<int> dl_floor_no
	{
		get
		{
			return this._dl_floor_no;
		}
		set
		{
			if ((this._dl_floor_no != value))
			{
				this.Ondl_floor_noChanging(value);
				this.SendPropertyChanging();
				this._dl_floor_no = value;
				this.SendPropertyChanged("dl_floor_no");
				this.Ondl_floor_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_room_no", DbType="Int")]
	public System.Nullable<int> dl_room_no
	{
		get
		{
			return this._dl_room_no;
		}
		set
		{
			if ((this._dl_room_no != value))
			{
				this.Ondl_room_noChanging(value);
				this.SendPropertyChanging();
				this._dl_room_no = value;
				this.SendPropertyChanged("dl_room_no");
				this.Ondl_room_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_description", DbType="VarChar(1000)")]
	public string dl_description
	{
		get
		{
			return this._dl_description;
		}
		set
		{
			if ((this._dl_description != value))
			{
				this.Ondl_descriptionChanging(value);
				this.SendPropertyChanging();
				this._dl_description = value;
				this.SendPropertyChanged("dl_description");
				this.Ondl_descriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ndmh_department_listing_ndmh_dep_list_image", Storage="_ndmh_dep_list_images", ThisKey="dl_id", OtherKey="dl_id")]
	public EntitySet<ndmh_dep_list_image> ndmh_dep_list_images
	{
		get
		{
			return this._ndmh_dep_list_images;
		}
		set
		{
			this._ndmh_dep_list_images.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_ndmh_dep_list_images(ndmh_dep_list_image entity)
	{
		this.SendPropertyChanging();
		entity.ndmh_department_listing = this;
	}
	
	private void detach_ndmh_dep_list_images(ndmh_dep_list_image entity)
	{
		this.SendPropertyChanging();
		entity.ndmh_department_listing = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ndmh_dep_list_images")]
public partial class ndmh_dep_list_image : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _dli_id;
	
	private string _dli_url;
	
	private string _dli_alt;
	
	private string _dli_desc;
	
	private System.Nullable<decimal> _dli_width;
	
	private System.Nullable<decimal> _dli_height;
	
	private int _dl_id;
	
	private string _dli_name;
	
	private EntityRef<ndmh_department_listing> _ndmh_department_listing;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondli_idChanging(int value);
    partial void Ondli_idChanged();
    partial void Ondli_urlChanging(string value);
    partial void Ondli_urlChanged();
    partial void Ondli_altChanging(string value);
    partial void Ondli_altChanged();
    partial void Ondli_descChanging(string value);
    partial void Ondli_descChanged();
    partial void Ondli_widthChanging(System.Nullable<decimal> value);
    partial void Ondli_widthChanged();
    partial void Ondli_heightChanging(System.Nullable<decimal> value);
    partial void Ondli_heightChanged();
    partial void Ondl_idChanging(int value);
    partial void Ondl_idChanged();
    partial void Ondli_nameChanging(string value);
    partial void Ondli_nameChanged();
    #endregion
	
	public ndmh_dep_list_image()
	{
		this._ndmh_department_listing = default(EntityRef<ndmh_department_listing>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dli_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int dli_id
	{
		get
		{
			return this._dli_id;
		}
		set
		{
			if ((this._dli_id != value))
			{
				this.Ondli_idChanging(value);
				this.SendPropertyChanging();
				this._dli_id = value;
				this.SendPropertyChanged("dli_id");
				this.Ondli_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dli_url", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string dli_url
	{
		get
		{
			return this._dli_url;
		}
		set
		{
			if ((this._dli_url != value))
			{
				this.Ondli_urlChanging(value);
				this.SendPropertyChanging();
				this._dli_url = value;
				this.SendPropertyChanged("dli_url");
				this.Ondli_urlChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dli_alt", DbType="VarChar(500)")]
	public string dli_alt
	{
		get
		{
			return this._dli_alt;
		}
		set
		{
			if ((this._dli_alt != value))
			{
				this.Ondli_altChanging(value);
				this.SendPropertyChanging();
				this._dli_alt = value;
				this.SendPropertyChanged("dli_alt");
				this.Ondli_altChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dli_desc", DbType="VarChar(500)")]
	public string dli_desc
	{
		get
		{
			return this._dli_desc;
		}
		set
		{
			if ((this._dli_desc != value))
			{
				this.Ondli_descChanging(value);
				this.SendPropertyChanging();
				this._dli_desc = value;
				this.SendPropertyChanged("dli_desc");
				this.Ondli_descChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dli_width", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> dli_width
	{
		get
		{
			return this._dli_width;
		}
		set
		{
			if ((this._dli_width != value))
			{
				this.Ondli_widthChanging(value);
				this.SendPropertyChanging();
				this._dli_width = value;
				this.SendPropertyChanged("dli_width");
				this.Ondli_widthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dli_height", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> dli_height
	{
		get
		{
			return this._dli_height;
		}
		set
		{
			if ((this._dli_height != value))
			{
				this.Ondli_heightChanging(value);
				this.SendPropertyChanging();
				this._dli_height = value;
				this.SendPropertyChanged("dli_height");
				this.Ondli_heightChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dl_id", DbType="Int NOT NULL")]
	public int dl_id
	{
		get
		{
			return this._dl_id;
		}
		set
		{
			if ((this._dl_id != value))
			{
				if (this._ndmh_department_listing.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Ondl_idChanging(value);
				this.SendPropertyChanging();
				this._dl_id = value;
				this.SendPropertyChanged("dl_id");
				this.Ondl_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dli_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string dli_name
	{
		get
		{
			return this._dli_name;
		}
		set
		{
			if ((this._dli_name != value))
			{
				this.Ondli_nameChanging(value);
				this.SendPropertyChanging();
				this._dli_name = value;
				this.SendPropertyChanged("dli_name");
				this.Ondli_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ndmh_department_listing_ndmh_dep_list_image", Storage="_ndmh_department_listing", ThisKey="dl_id", OtherKey="dl_id", IsForeignKey=true)]
	public ndmh_department_listing ndmh_department_listing
	{
		get
		{
			return this._ndmh_department_listing.Entity;
		}
		set
		{
			ndmh_department_listing previousValue = this._ndmh_department_listing.Entity;
			if (((previousValue != value) 
						|| (this._ndmh_department_listing.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._ndmh_department_listing.Entity = null;
					previousValue.ndmh_dep_list_images.Remove(this);
				}
				this._ndmh_department_listing.Entity = value;
				if ((value != null))
				{
					value.ndmh_dep_list_images.Add(this);
					this._dl_id = value.dl_id;
				}
				else
				{
					this._dl_id = default(int);
				}
				this.SendPropertyChanged("ndmh_department_listing");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
