using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class _Default : System.Web.UI.Page
{
    faqsClass objFaqs = new faqsClass();
    protected void Page_Load(object sender, EventArgs e)
    {
        
        
    }

     //this method was generated by AJAX control toolkit to create the list of auto-fill suggestions
     //inspired by example from http://www.asp.net/ajaxlibrary/act_AutoComplete_Simple.ashx
    [System.Web.Services.WebMethodAttribute(), System.Web.Script.Services.ScriptMethodAttribute()]
    public static string[] GetCompletionList(string prefixText, int count, string contextKey)
    {
        faqsClass objFaqs = new faqsClass();
        
        // set titles array that will be used in the return statement to routine that sets list of titles from db into an array.  
        string[] titles = objFaqs.getAllFaqTitles(); 

        // Return matching movies  
        return (from t in titles where t.StartsWith(prefixText, StringComparison.CurrentCultureIgnoreCase) select t).Take(count).ToArray();
    }

    
   

}